# Generated by Django 2.1.5 on 2019-01-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="core.Student"
            ),
        )
    ]
